title: Igor Kalders
logo: logo.svg 
description: Wander around dust collected over the years

author:
  name: Igor Kalders
  image: 01.jpg
  say-hello: Voetsporen
  bio: Deze blog werd ooit actief onderhouden maar ging verloren.
    Na een avondje forensisch onderzoek op
    <a href="https://web.archive.org/web/20091203032957/http://kalders.be/">archive.org</a>
    werd hij in zijn historische ere hersteld.

twitter: https://twitter.com/GrimaceODespair
facebook: https://www.facebook.com/igor.kalders